name: Pytest Workflow

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Exec setup script
        run: chmod +x ./setup.sh && ./setup.sh

      - name: Generate .env files from secrets
        run: |
          echo "${{ secrets.ENV_BACKEND }}" | base64 -d > backend/.env
          echo "${{ secrets.ENV_MARIADB }}" | base64 -d > mariadb/.env
          echo "${{ secrets.ENV_NLP }}" | base64 -d > nlp/.env

      - name: Set up Docker Buildx (opzionale)
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose up mariadb backend -d --build

      - name: Wait for containers to be ready
        run: sleep 20

      - name: Run tests inside backend container
        # usiamo python -m perche cosi include . in sys.path automaticamente
        run: docker compose exec -T backend python -m pytest

      - name: Tear down containers
        if: always()
        run: docker compose down
