name: Docker tests

on:
  push:
    branches: [test]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Exec setup script
        run: chmod +x ./setup.sh && ./setup.sh

      - name: Set up Docker Buildx (opzionale)
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for containers to be ready
        run: sleep 20

      - name: Run tests inside backend container
        # usiamo python -m perche cosi include . in sys.path automaticamente
        run: docker compose exec -T backend python -m pytest

      - name: Tear down containers
        if: always()
        run: docker compose down
